# Generated by Django 4.2.8 on 2023-12-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_assistenza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk', models.CharField(max_length=100000)),
            ],
        ),
    ]
