# Generated by Django 4.2.8 on 2023-12-19 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_assistenza', '0002_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
