# Generated by Django 4.2.8 on 2023-12-19 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_assistenza', '0003_quest_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
