# Generated by Django 4.2.7 on 2023-12-04 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0003_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 10, 46, 32, 469905, tzinfo=datetime.timezone.utc)),
        ),
    ]
