# Generated by Django 4.2.7 on 2023-12-04 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0004_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 11, 49, 16, 762070, tzinfo=datetime.timezone.utc)),
        ),
    ]
