# Generated by Django 4.2.7 on 2023-12-05 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0006_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 10, 55, 53, 93620, tzinfo=datetime.timezone.utc)),
        ),
    ]
