# Generated by Django 4.2.7 on 2023-12-05 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0008_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 11, 38, 44, 791873, tzinfo=datetime.timezone.utc)),
        ),
    ]
