# Generated by Django 4.2.7 on 2023-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_utenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
