# Generated by Django 4.2.8 on 2023-12-10 16:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('min_sale', models.IntegerField(default=1)),
                ('timer', models.DateTimeField(default=datetime.datetime(2023, 12, 10, 17, 12, 5, 625177, tzinfo=datetime.timezone.utc))),
                ('offer', models.IntegerField(default=0)),
            ],
        ),
    ]
