# Generated by Django 4.2.8 on 2023-12-10 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 17, 41, 12, 550084, tzinfo=datetime.timezone.utc)),
        ),
    ]
