# Generated by Django 4.2.8 on 2023-12-15 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0002_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 10, 16, 51, 814728, tzinfo=datetime.timezone.utc)),
        ),
    ]
