# Generated by Django 4.2.8 on 2023-12-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0005_rename_tk_quest_alter_item_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 11, 33, 47, 844589, tzinfo=datetime.timezone.utc)),
        ),
    ]
