# Generated by Django 4.2.8 on 2023-12-17 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_oggetti', '0006_alter_item_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(default='Nessuno', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 20, 27, 14, 236155, tzinfo=datetime.timezone.utc)),
        ),
    ]
