# Generated by Django 4.2.7 on 2023-11-22 20:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('min_sale', models.IntegerField(default=1)),
                ('timer', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 21, 46, 21, 132025, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
