# Generated by Django 4.2.7 on 2023-11-22 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 21, 46, 47, 590179, tzinfo=datetime.timezone.utc)),
        ),
    ]
