# Generated by Django 4.2.7 on 2023-11-23 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0003_alter_todoitem_timer_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 17, 37, 40, 204595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
