# Generated by Django 4.2.7 on 2023-11-25 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auctions', '0004_alter_todoitem_timer_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 4, 53, 593345, tzinfo=datetime.timezone.utc)),
        ),
    ]
