# Generated by Django 4.2.7 on 2023-11-25 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0007_alter_todoitem_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 19, 3, 16, 570323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
